# Change these first
owner: andres-chirinos # Your GitHub organization or username, where this repository lives
repo: monitorbolivia # The name of this repository

sites:
  - name: Agencia Nacional de Hidrocarburos (ANH)
    url: https://www.anh.gob.bo
    __dangerous__insecure: true
  - name: Servicio General de Identificación Personal (SEGIP)
    url: https://www.segip.gob.bo
    __dangerous__insecure: true
  - name: Servicio de Impuestos Nacionales (SIN)
    url: https://www.impuestos.gob.bo
    __dangerous__insecure: true
  - name: Ministerio de Educación
    url: https://www.minedu.gob.bo
    __dangerous__insecure: true
  - name: Tribunal Supremo Electoral (TSE)
    url: https://www.oep.org.bo
    __dangerous__insecure: true
  - name: Asamblea Legislativa Plurinacional de Bolivia
    url: https://diputados.gob.bo/
    __dangerous__insecure: true
  - name: Cámara de Senadores
    url: https://www.senado.gob.bo/
    __dangerous__insecure: true
  - name: Cámara de Diputados
    url: https://www.diputados.bo
    __dangerous__insecure: true
  - name: Gaceta Oficial del Estado Plurinacional de Bolivia
    url: http://www.gacetaoficialdebolivia.gob.bo/
    __dangerous__insecure: true
    maxResponseTime: 5000
  - name: Defensoría del Pueblo
    url: https://www.defensoria.gob.bo
    __dangerous__insecure: true
  - name: Contraloría General del Estado
    url: https://www.contraloria.gob.bo
    __dangerous__insecure: true
  - name: Procuraduría General del Estado
    url: https://www.procuraduria.gob.bo
    __dangerous__insecure: true
    maxResponseTime: 5000
  - name: Universidad Mayor de San Andrés (UMSA)
    url: https://www.umsa.bo
    __dangerous__insecure: true
  - name: Universidad Técnica de Oruro (UTO)
    url: https://www.uto.edu.bo
    __dangerous__insecure: true
  - name: Sistema de Universidades Bolivianas (CEUB)
    url: https://www.ceub.edu.bo
    __dangerous__insecure: true
  - name: Administradora Boliviana de Carreteras (ABC)
    url: https://www.viasbolivia.gob.bo/
    __dangerous__insecure: true
    maxResponseTime: 5000
  - name: Empresa Nacional de Telecomunicaciones (ENTEL)
    url: https://www.entel.bo
    __dangerous__insecure: true
    maxResponseTime: 5000
  - name: Banco Unión
    url: https://www.bancounion.com.bo
    __dangerous__insecure: true
  - name: Banco Central de Bolivia (BCB)
    url: https://www.bcb.gob.bo
    __dangerous__insecure: true
  - name: Bolivia TV (BTV)
    url: https://www.boliviatv.bo
    __dangerous__insecure: true
  - name: Boliviana de Aviación (BoA)
    url: https://www.boa.bo
    __dangerous__insecure: true
  - name: Seguros y Reaseguros Personales UNIVIDA
    url: https://www.univida.bo
    __dangerous__insecure: true
  - name: Yacimientos Petrolíferos Fiscales Bolivianos (YPFB)
    url: https://www.ypfb.gob.bo
    __dangerous__insecure: true
  - name: Autoridad de Supervisión del Sistema Financiero (ASFI)
    url: https://www.asfi.gob.bo
    __dangerous__insecure: true
  - name: Aduana Nacional de Bolivia
    url: https://www.aduana.gob.bo
    __dangerous__insecure: true
  - name: Ministerio de Salud y Deportes
    url: https://www.minsalud.gob.bo
    __dangerous__insecure: true
  - name: Policía Boliviana
    url: https://www.policia.bo
    __dangerous__insecure: true
  - name: Ministerio de Justicia y Transparencia Institucional
    url: https://www.justicia.gob.bo
    __dangerous__insecure: true
    maxResponseTime: 5000
  - name: Autoridad de Fiscalización y Control de Pensiones y Seguros (APS)
    url: https://www.aps.gob.bo
    __dangerous__insecure: true
  - name: Instituto Nacional de Estadística (INE)
    url: https://www.ine.gob.bo
    __dangerous__insecure: true
  - name: Ministerio de Defensa
    url: https://www.mindef.gob.bo
    __dangerous__insecure: true
    maxResponseTime: 5000
  - name: Ministerio de Obras Públicas, Servicios y Vivienda
    url: https://www.oopp.gob.bo
    __dangerous__insecure: true
  - name: Dirección General de Aeronáutica Civil (DGAC)
    url: https://www.dgac.gob.bo
    __dangerous__insecure: true
  - name: Servicio Nacional de Propiedad Intelectual (SENAPI)
    url: https://www.senapi.gob.bo/
    __dangerous__insecure: true
  - name: Autoridad de Fiscalización de Electricidad y Tecnología Nuclear (AETN)
    url: https://www.aetn.gob.bo
    __dangerous__insecure: true
  - name: Mi Teleférico
    url: https://www.miteleferico.bo
    __dangerous__insecure: true
  - name: Servicio Nacional de Meteorología e Hidrología (SENAMHI)
    url: https://www.senamhi.gob.bo
    __dangerous__insecure: true
  - name: Agencia Boliviana Espacial (ABE)
    url: https://www.abe.bo
    __dangerous__insecure: true
  - name: Caja Nacional de Salud (CNS)
    url: https://www.cns.gob.bo
    __dangerous__insecure: true
  - name: Autoridad de Regulación y Fiscalización de Telecomunicaciones y Transportes (ATT)
    url: https://www.att.gob.bo
    __dangerous__insecure: true
  - name: Empresa Nacional de Electricidad (ENDE)
    url: http://www.ende.bo
    maxResponseTime: 5000
    __dangerous__insecure: true
  - name: Instituto Boliviano de Comercio Exterior (IBCE)
    url: https://www.ibce.org.bo
    __dangerous__insecure: true
  - name: Ministerio de Medio Ambiente y Agua
    url: https://www.mmaya.gob.bo
    __dangerous__insecure: true
  - name: Agencia para el Desarrollo de la Sociedad de la Información en Bolivia (ADSIB)
    url: https://www.adsib.gob.bo
    __dangerous__insecure: true
  - name: Ministerio de Relaciones Exteriores
    url: https://www.rree.gob.bo
    __dangerous__insecure: true
  - name: Sistema de Calidad de Aire del Gobierno Autonomo Municipal de La Paz
    url: http://airecalidad.lapaz.bo/
    __dangerous__insecure: true

status-website:
  links:
    - rel: stylesheet
      href: https://raw.githubusercontent.com/andres-chirinos/monitorbolivia/master/assets/style.css
  cname: monitorbolivia.andreschirinos.tech
  logoUrl: https://raw.githubusercontent.com/andres-chirinos/monitorbolivia/master/assets/logo.png
  name: Monitor de Estado de Paginas de Bolivia
  description: Monitoreo en tiempo real del estado de las páginas web de Bolivia.
  introTitle: "Monitoreo en tiempo real del estado de las páginas web de Bolivia."
  introMessage: Consulta el estado en línea de las páginas web gubernamentales y servicios de Bolivia.
  favicon: https://raw.githubusercontent.com/andres-chirinos/monitorbolivia/master/assets/icon.png
  faviconSvg: https://raw.githubusercontent.com/andres-chirinos/monitorbolivia/master/assets/icon.svg
  navbar:
    - title: Sobre nosotros
      href: https://andreschirinos.tech/
    - title: Repositorio de GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  activeIncidents: Incidentes Activos
  allSystemsOperational: Todos los sistemas funcionando
  incidentReport: "Reporte del incidente #$NUMBER →"
  activeIncidentSummary: Iniciado en $DATE con $POSTS comentarios
  incidentTitle: Incidente $NUMBER
  incidentDetails: Detalles del incidente
  incidentFixed: Arreglado
  incidentOngoing: En proceso
  incidentOpenedAt: Iniciado en
  incidentClosedAt: Cerrado en
  incidentViewOnGitHub: Ver y seguir en GitHub
  incidentCommentSummary: Enviado el $DATE por $AUTHOR
  incidentBack: ← Volver a todos los incidentes
  pastIncidents: Incidentes pasados
  pastIncidentsResolved: Resuelto en $MINUTES minutos con $POSTS comentarios
  liveStatus: Estado en vivo
  overallUptime: "Tiempo de actividad global: $UPTIME"
  overallUptimeTitle: Tiempo de actividad global
  averageResponseTime: "Tiempo medio de respuesta: $TIMEms"
  averageResponseTimeTitle: Promedio de tiempo de respuesta
  sevelDayResponseTime: Tiempo de respuesta de 7 días
  responseTimeMs: Tiempo de respuesta (ms)x
  up: En linea
  down: Fuera de linea
  degraded: Degradado
  ms: ms
  loading: Cargando...
  navGitHub: GitHub
  footer: Esta pagina es de [codigo abierto]($REPO), proveida por [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Tiempo de espera excedido
  rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
  rateLimitExceededWhatDoesErrorMean: What does this error mean?
  rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
  rateLimitExceededErrorHowCanFix: How can I fix it?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
  rateLimitExceededHasSet: You have a personal access token set.
  rateLimitExceededRemoveToken: Remove token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copy and paste your token
  rateLimitExceededSaveToken: Save token
  errorTitle: Un error ha ocurrido
  errorIntro: Un error ha ocurrido intentando obtener los ultimos detalles de estado.
  errorText: Vuelve a intentarlo más tarde o revisa el [repositorio de GitHub]($REPO) para más información.
  errorHome: Ve al inicio
  pastScheduledMaintenance: Mantenimientos programados pasados
  scheduledMaintenance: Mantenimiento programado
  scheduledMaintenanceSummaryStarted: Comenzó en $DATE durante $DURATION minutos
  scheduledMaintenanceSummaryStarts: Comienza en $DATE durante $DURATION minutos
  startedAt: Comenzó en
  startsAt: Comienza en
  duration: Duración
  durationMin: $DURATION minutos
  incidentCompleted: Completado
  incidentScheduled: Programado
  duration24H: 24h
  duration7D: 7d
  duration30D: 30d
  duration1Y: 1y
  durationAll: desde el inicio
  locale: es-ES

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

commitMessages:
  commitAuthorName: "Upptime Bot"
  commitAuthorEmail: "upptime@koj.co"
